Repository jscoq/jscoq, pull requests merged in 2019-06, with the labels that each got.

#113 Focus next bullet with
  CHANGES.md
  coq-js/jser_goals.ml
  coq-js/serapi_goals.ml
  coq-js/serapi_goals.mli
  ui-css/coq-base.css
  ui-js/format-pprint.js
Labels: kind: enhancement, kind: ui

#112 Open/save file dialogs
  CHANGES.md
  README.md
  examples/scratchpad.html
  ui-css/coq-base.css
  ui-css/coq-dark.css
  ui-css/coq-light.css
  ui-js/cm-provider.js
  ui-js/coq-manager.js
  ui-js/jscoq-loader.js
Labels: kind: enhancement, kind: ui

#109 Asynchronous document model
  CHANGES.md
  ui-js/cm-provider.js
  ui-js/coq-manager.js
Labels: kind: cleanup, kind: enhancement, kind: fix

#115 [addons] Fix Software Foundations addon file.
  coq-addons/sf.addon
Labels: kind: build, kind: packaging

#120 [community] Add a Code of Conduct.
  CODE_OF_CONDUCT.md
Labels: kind: documentation, kind: meta

#118 Tweaking the key bindings
  ui-css/coq-base.css
  ui-js/cm-provider.js
  ui-js/coq-manager.js
Labels: kind: ui

#123 Update README with keys and open/save.
  README.md
Labels: kind: documentation
