Repository jscoq/jscoq, pull requests merged in 2019-04, with the labels that each got.

#65 Mklibfs overhaul
  coq-jslib/dune
  coq-jslib/mklibfs.ml
  dune
Labels: kind: build, kind: cleanup, kind: packaging

#68 Removing the avoid-vm patch
  Makefile
  etc/patches/avoid-vm.patch
Labels: kind: build, kind: fix, upstream

#70 `Compile` command.
  coq-js/dune
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/js_stub/marshal.js
  coq-js/jscoq_worker.ml
  coq-js/jslibmng.ml
  ui-js/coq-cli.js
Labels: in-progess, kind: enhancement, kind: packaging, upstream

#72 On-the-fly package build prototype
  coq-js/dune
  coq-js/icoq.ml
  coq-js/js_stub/str.js
  coq-js/jscoq_worker.ml
  coq-jslib/mkdeps.js
  etc/patches/lazy-noinline.patch
  package-lock.json
  package.json
  ui-js/coq-build.js
  ui-js/coq-cli.js
  ui-js/jscoq.js
Labels: kind: build, kind: enhancement

#77 [coq] Update to JSOO 3.4.0
  CHANGES.md
  coq-js/js_stub/coq_vm.js
  coq-js/js_stub/str.js
  coq-js/js_stub/unix.js
  coq-js/jslibmng.ml
  jscoq.opam
Labels: kind: js-backend, kind: packaging

#76 Miscellanous updates, checking CI.
  .gitignore
  .travis.yml
  Makefile
  coq-js/Makefile
  index.html
  jscoq.opam
Labels: kind: cleanup

#78 [bugfix] Backported `Lazy.force` patch.
  Makefile
  etc/patches/lazy-noinline.patch
Labels: kind: fix

#79 [general] Release 0.9 !
  CHANGES.md
  README.md
  coq-js/jscoq_worker.ml
  etc/notes/announce-0.9.md
  package-lock.json
  package.json
Labels: kind: meta

#83 [doc] Tweak to build notes, closes #35
  docs/build.md
Labels: kind: build, kind: documentation

#41 [ci] [travis] Initial version of OSX testing.
  .travis.yml
  etc/toolchain-setup.sh
Labels: kind: build, kind: ci
