Repository jscoq/jscoq, pull requests merged in 2019-03, with the labels that each got.

#40 Mega-PR with a slew of new features
  .gitignore
  CHANGES.md
  LICENSE
  Makefile
  README.md
  coq-js/Makefile
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/jscoq.js
  coq-js/jscoq_doc.ml
  coq-js/jscoq_doc.mli
  coq-js/jscoq_worker.ml
  coq-js/jser_feedback.ml
  coq-js/jser_names.ml
  coq-js/jslib.ml
  coq-js/jslib.mli
  coq-js/jslibmng.ml
  coq-js/jslibmng.mli
  coq-js/patches/avoid-vm.patch
  coq-js/patches/trampoline.patch
  coq-libjs/coq_vm.js
  coq-libjs/str.js
  coq-libjs/unix.js
  coq-tools/dftlibs.ml
  coq-tools/mkdeps.js
  coq-tools/mklibjson.ml
  coq-tools/mkpkg.js
  docs/Build.md
  examples/dft.css
  examples/gentle-intro.html
  newide.html
  package-lock.json
  package.json
  ui-css/coq-base.css
  ui-css/coq-light.css
  ui-css/coq-log.css
  ui-images/log-error.png
  ui-images/log-info.png
  ui-images/log-notice.png
  ui-images/log-warn.png
  ui-js/addon/company-coq.js
  ui-js/cm-provider.js
  ui-js/coq-layout-classic.js
  ui-js/coq-manager.js
  ui-js/coq-packages.js
  ui-js/format-pprint.js
  ui-js/jscoq-loader.js
  ui-js/mode/coq-mode.js
  ui-js/symbols/coq-arith.symb.json
  ui-js/symbols/init.symb.json
Labels: enhancement

#43 Cleanup: libjs primitives and image files
  LICENSE
  coq-libjs/coq_vm.js
  coq-libjs/str.js
  coq-libjs/unix.js
  ui-images/assets/arrow.svg
  ui-images/assets/circle-crimson.svg
  ui-images/assets/icons.ai
  ui-images/assets/log-error.xcf
  ui-images/assets/mark-error.svg
  ui-images/log-error.png
Labels: kind: cleanup

#44 [jscoq] Wait to send coqInfo message until all libinfo has been sent.
  coq-js/jscoq.js
  coq-js/jscoq_worker.ml
  coq-tools/dftlibs.ml
  docs/Build.md
  examples/iris.html
  ui-js/coq-manager.js
Labels: kind: fix

#48 [npm] Update bootstrap dependency to fix security issue.
  package-lock.json
  package.json
Labels: kind: packaging

#50 [build] Cleanup old files and libraries that are now managed by npm.
  examples/Coq86.html
  examples/Stlc.html
  examples/dft.html
  examples/equations_intro.html
  examples/iris.html
  newhott.html
  ui-external/bootstrap-3.3.5-dist/css/bootstrap-theme.css
  ui-external/bootstrap-3.3.5-dist/css/bootstrap-theme.css.map
  ui-external/bootstrap-3.3.5-dist/css/bootstrap-theme.min.css
  ui-external/bootstrap-3.3.5-dist/css/bootstrap.css
  ui-external/bootstrap-3.3.5-dist/css/bootstrap.css.map
  ui-external/bootstrap-3.3.5-dist/css/bootstrap.min.css
  ui-external/bootstrap-3.3.5-dist/fonts/glyphicons-halflings-regular.eot
  ui-external/bootstrap-3.3.5-dist/fonts/glyphicons-halflings-regular.svg
  ui-external/bootstrap-3.3.5-dist/fonts/glyphicons-halflings-regular.ttf
  ui-external/bootstrap-3.3.5-dist/fonts/glyphicons-halflings-regular.woff
  ui-external/bootstrap-3.3.5-dist/fonts/glyphicons-halflings-regular.woff2
  ui-external/bootstrap-3.3.5-dist/js/bootstrap.js
  ui-external/bootstrap-3.3.5-dist/js/bootstrap.min.js
  ui-external/bootstrap-3.3.5-dist/js/npm.js
  ui-external/bootstrap.min.css
  ui-external/bootstrap.min.js
  ui-external/d3.min.js
  ui-external/interact.min.js
  ui-external/jquery-2.2.0.min.js
  ui-external/jquery.gridster.min.css
  ui-external/jquery.gridster.min.js
  ui-external/pace/pace.css
  ui-external/pace/pace.min.js
  worker.html
Labels: kind: packaging

#49 [build] Fix `dist` make target.
  Makefile
  build.sh
  config.mk
  coq-js/Makefile
  coq-patches/avoid-vm.patch
  coq-patches/trampoline.patch
Labels: kind: build, kind: packaging

#54 Inspect command implementation
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/jscoq.js
  coq-js/jscoq_worker.ml
  coq-libjs/str.js
  package-lock.json
  package.json
  ui-js/coq-manager.js
Labels: kind: enhancement, kind: lsp

#55 Node.js command-line interface (PoC)
  Makefile
  coq-js/jscoq.js
  coq-tools/mkpkg.js
  package-lock.json
  package.json
  ui-js/coq-cli.js
  ui-js/coq-manager.js
Labels: kind: build, kind: enhancement

#56 Separate addons
  .travis.yml
  Makefile
  build.sh
  config.mk
  coq-addons/mathcomp.addon
  coq-js/Makefile
  coq-tools/dftlibs.ml
  coq-tools/mklibjson.ml
  docs/Build.md
Labels: kind: build, kind: cleanup, kind: packaging

#60 [ci] [gitlab] Add basic GitLab CI.
  .gitlab-ci.yml
Labels: kind: ci

#58 [build] General Cleanups cherry-picked from the Dune PR (#37)
  .travis.yml
  LICENSE
  Makefile
  Makefile.addons
  README.md
  coq-addons/common.mk
  coq-addons/dsp.addon
  coq-addons/elpi.addon
  coq-addons/equations.addon
  coq-addons/iris.addon
  coq-addons/ltac2.addon
  coq-addons/mathcomp.addon
  coq-addons/odd-order.addon
  coq-js/Makefile
  coq-js/js_stub/coq_vm.js
  coq-js/js_stub/mutex.js
  coq-js/js_stub/str.js
  coq-js/js_stub/unix.js
  coq-tools/dftlibs.ml
  docs/Build.md
  etc/opam/4.02.3+32bit/4.02.3+32bit.comp
  etc/opam/4.02.3+32bit/4.02.3+32bit.descr
  etc/opam/4.03.0+32bit/4.03.0+32bit.comp
  etc/opam/4.03.0+32bit/4.03.0+32bit.descr
  etc/opam/4.06.0+32bit/4.06.0+32bit.comp
  etc/opam/4.06.0+32bit/4.06.0+32bit.descr
  etc/patches/avoid-vm.patch
  etc/patches/trampoline.patch
  examples/equations_intro.html
  examples/hott.html
  examples/mirror-core-rtac-demo.html
  examples/mirrorcore.html
  examples/mtac_tutorial.html
  index.html
  jscoq.opam
  package.json
  toolchain-setup.sh
  ui-js/jscoq-loader.js
  ui-js/jscoq.js
  worker.html
Labels: kind: build, kind: packaging

#63 [addons] Resurrect Software Foundations
  config.mk
  coq-addons/sf.addon
  coq-tools/dftlibs.ml
  examples/Stlc.html
  ui-js/coq-manager.js
Labels: kind: packaging

#57 Addons cleanup
  .travis.yml
  coq-addons/mathcomp.addon
  coq-addons/odd-order.addon
  coq-external/dsp/Makefile
Labels: kind: build

#62 [misc] [doc] Improve CHANGES + a couple of minor nits / fixes.
  CHANGES.md
  coq-js/.merlin
  index.html
Labels: kind: build, kind: documentation

#59 [jscoq] Provide more detailed information about goals (#27)
  CHANGES.md
  coq-js/Makefile
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/jscoq_worker.ml
  coq-js/jser_goals.ml
  coq-js/serapi_goals.ml
  coq-js/serapi_goals.mli
  ui-css/coq-base.css
  ui-js/coq-layout-classic.js
  ui-js/coq-manager.js
  ui-js/format-pprint.js
Labels: in-progess, kind: enhancement, kind: ui

#64 Some cleanup in paths
  .travis.yml
  Makefile
  coq-external/dsp/Makefile
  coq-js/dune
  coq-js/jscoq_worker.ml
  coq-jslib/mklibfs.ml
  dune
  etc/patches/avoid-vm.patch
  etc/patches/trampoline.patch
  jscoq.opam
  ui-js/coq-cli.js
Labels: kind: build, kind: cleanup, kind: packaging
