Repository jscoq/jscoq, pull requests merged in 2019-05, with the labels that each got.

#95 Proposed new, decentralized package building
  Makefile
  coq-addons/common.mk
  coq-addons/mathcomp.addon
  coq-addons/sf.addon
  coq-jslib/dftlibs.ml
  coq-jslib/mkpkg.js
  ui-js/coq-build.js
Labels: kind: build, kind: packaging

#98 [feature] Build in browser
  .gitignore
  CHANGES.md
  Makefile
  coq-js/jscoq_doc.ml
  coq-js/jscoq_doc.mli
  coq-js/jscoq_worker.ml
  dune
  package-lock.json
  package.json
  project-builder.html
  ui-css/project.css
  ui-js/components/file-list.js
  ui-js/components/problem-list.js
  ui-js/coq-build.js
  ui-js/coq-cli.js
  ui-js/coq-packages.js
  ui-js/dune
  ui-js/format-pprint.js
  ui-js/fs-interface.js
  ui-js/jscoq-loader.js
  ui-js/jscoq.js
Labels: kind: enhancement, kind: packaging

#102 Emulation of timeout
  CHANGES.md
  Makefile
  etc/patches/timeout.patch
Labels: kind: enhancement, kind: js-backend, upstream

#103 Dark theme for panel + new toolbar icons
  CHANGES.md
  LICENSE
  ui-css/coq-base.css
  ui-css/coq-dark.css
  ui-css/coq-light.css
  ui-images/assets/arrow-bar.svg
  ui-images/assets/arrow.svg
  ui-images/assets/text-cursor.svg
  ui-images/assets/to-cursor.svg
  ui-images/down.png
  ui-images/github.png
  ui-images/log-info.png
  ui-images/log-notice.png
  ui-images/themes/dark/github.png
  ui-images/to-cursor.png
  ui-images/up.png
  ui-js/coq-layout-classic.js
  ui-js/jscoq-loader.js
Labels: kind: ui

#104 [libs] Don't load extraction and funind in `init`.
  coq-jslib/dftlibs.ml
Labels: kind: packaging, upstream

#107 Printing support
  CHANGES.md
  ui-css/coq-base.css
  ui-css/coq-log.css
  ui-js/jscoq-loader.js
Labels: kind: ui

#110 Fixing Travis
  .travis.yml
Labels: kind: ci

#108 Support for Coq options
  CHANGES.md
  README.md
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/jscoq_worker.ml
  ui-js/coq-manager.js
  ui-js/jscoq.js
Labels: kind: enhancement
