Repository jscoq/jscoq, pull requests merged in 2020-03, with the labels that each got.

#159 Tutorial on embedding jsCoq using npm
  README.md
  docs/embedding.md
  docs/inject-jscoq.gawk
  docs/npm-landing-screenshot.png
  docs/npm-landing.html
  examples/npm-template.html
Labels: kind: documentation

#163 [npm] Upgrade some deps to silence warnings.
  package-lock.json
Labels: kind: packaging

#165 Trampolining code in constr_matching as well.
  etc/patches/trampoline.patch
Labels: kind: fix, kind: js-backend

#166 Stack overflow in Require
  Makefile
  etc/patches/cps.patch
Labels: kind: fix

#169 [build] Fix a few warnings, adjust flags.
  coq-js/icoq.ml
  coq-js/jscoq_proto.ml
  coq-js/jscoq_worker.ml
  coq-js/jslibmng.ml
  dune
  etc/patches/timeout.patch
Labels: kind: build

#167 Compat_32 marshalling
  etc/patches/coerce-32bit.patch
Labels: kind: cleanup

#164 Multiple package paths
  CHANGES.md
  README.md
  ui-js/coq-manager.js
  ui-js/coq-packages.js
Labels: kind: enhancement, kind: packaging

#174 Fix project-builder
  project-builder.html
  ui-css/components/file-list.css
  ui-css/project.css
  ui-js/components/file-list.js
  ui-js/components/problem-list.js
  ui-js/coq-build.js
  ui-js/coq-cli.js
  ui-js/coq-packages.js
  ui-js/jscoq.js
Labels: kind: fix
