Repository jscoq/jscoq, pull requests merged in 2020-04, with the labels that each got.

#173 [contributing] Some notes about review / merge
  CONTRIBUTING.md
Labels: kind: documentation, kind: meta

#170 ☘️ Freshen up the look of the landing page.
  index.html
  ui-images/js-logo.svg
  ui-js/coq-layout-classic.js
Labels: kind: documentation

#178 [build] Fix missing dependency on addons install directory.
  dune
Labels: kind: build, kind: fix

#181 [build] Always rebuild coq-pkgs
  dune
Labels: kind: build, kind: fix

#180 [build] Pin to Coq 8.11.1
  CHANGES.md
  Makefile
Labels: kind: build, kind: packaging

#182 [readme] Update for 8.11 and recent changes.
  README.md
  docs/developing.md
  docs/embedding.md
  docs/papers.md
Labels: kind: documentation

#184 Revised package build system
  .travis.yml
  Makefile
  coq-jslib/build/batch.ts
  coq-jslib/build/coqdep.ts
  coq-jslib/build/fsif.ts
  coq-jslib/build/project.ts
  coq-jslib/build/workspace.ts
  coq-jslib/cli.ts
  coq-jslib/metadata/coq-pkgs.json
  coq-jslib/mkdeps.js
  coq-jslib/mkpkg.js
  dune
  package-lock.json
  package.json
  project-builder.html
  tsconfig.json
  webpack.config.js
Labels: in-progress, kind: build, kind: cleanup

#183 Tweak deprettify
  ui-js/cm-provider.js
Labels: kind: fix, kind: ui

#177 More accurate location of error indicator
  CHANGES.md
  ui-css/coq-base.css
  ui-css/coq-dark.css
  ui-css/coq-light.css
  ui-js/cm-provider.js
  ui-js/coq-manager.js
Labels: kind: enhancement, kind: ui
