Repository jscoq/jscoq, pull requests merged in 2020-01, with the labels that each got.

#143 adding separation logic course in list of users
  README.md
Labels: kind: documentation

#144 [jscoq] [build] Update toolchain
  coq-js/dune
  dune
  dune-project
  dune-workspace
  dune-workspace-64
  jscoq.opam
Labels: kind: build

#145 [jscoq] Release 0.10.1
  CHANGES.md
  README.md
  coq-js/jscoq_version.ml
  coq-js/jscoq_worker.ml
  package.json
Labels: kind: meta, kind: packaging
