Repository jscoq/jscoq, pull requests merged in 2020-09, with the labels that each got.

#200 [travis] Don't use incorrect git submodule call
  .travis.yml
Labels: kind: testing

#202 More Project pane
  CHANGES.md
  coq-js/icoq.ml
  coq-js/icoq.mli
  coq-js/jscoq_proto.ml
  coq-js/jscoq_worker.ml
  coq-js/jslibmng.ml
  coq-js/jslibmng.mli
  coq-jslib/build/batch.ts
  coq-jslib/build/fsif.ts
  coq-jslib/build/project.ts
  examples/scratchpad.html
  ui-css/coq-base.css
  ui-css/project.css
  ui-js/components/file-list.js
  ui-js/coq-layout-classic.js
  ui-js/coq-manager.js
  ui-js/coq-packages.js
  ui-js/ide-project.js
  ui-js/jscoq.js
Labels: kind: ui

#208 [readme] mailing list -> Zulip
  README.md
Labels: kind: documentation
