Repository jscoq/jscoq, pull requests merged in 2021-02, with the labels that each got.

#218 Restore Unit Tests
  .gitignore
  coq-js/jscoq_worker.ml
  coq-js/jslibmng.ml
  coq-jslib/build/project.ts
  coq-jslib/cli.ts
  dune
  package-lock.json
  package.json
  tests/main.js
  ui-js/coq-build.js
  ui-js/coq-cli.js
  ui-js/fs-interface.js
  ui-js/headless.ts
  ui-js/jscoq.js
  ui-js/webpack.config.js
  webpack.config.js
Labels: kind: fix, kind: testing

#217 Allowing hidden snippets in documents
  ui-js/cm-provider.js
  ui-js/coq-manager.js
Labels: kind: enhancement, kind: ui

#225 [build] Don't use bash to run simple commands.
  dune
  ui-js/dune
Labels: kind: build

#226 [build] Bump required compiler version to 4.10.2
  CHANGES.md
  docs/build.md
  etc/docker/Dockerfile
  etc/toolchain-setup.sh
  jscoq.opam
Labels: dependencies, kind: build, kind: packaging
