Repository jscoq/jscoq, pull requests merged in 2025-09, with the labels that each got.

#403 [opam] Avoid lwt 5.9.2
  jscoq.opam
Labels: kind: fix, dependencies

#400 Fix type error and scratchpad
  .github/workflows/ci.yml
  backend/coq-worker.ts
  etc/toolchain-setup.sh
  examples/scratchpad.html
  frontend/classic/js/cm-provider-container.ts
  frontend/classic/js/cm-provider.ts
  frontend/classic/js/coq-editor.ts
  frontend/classic/js/coq-manager.ts
  frontend/classic/js/coq-packages.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: kind: fix

#412 [cypress] [test] Test for basic goals command.
  cypress/e2e/common.ts
Labels: kind: testing, part: test suite

#406 [misc] Remove vue code, cleanup npm deps
  .gitignore
  Makefile
  dune
  etc/knip.json
  frontend/classic/js/addon/collab/hastebin.js
  frontend/classic/js/addon/collab/index.ts
  frontend/classic/js/addon/public-path.js
  frontend/classic/js/components/context-menu/context-menu-item.vue
  frontend/classic/js/components/context-menu/context-menu.css
  frontend/classic/js/components/context-menu/context-menu.vue
  frontend/classic/js/components/file-list/file.vue
  frontend/classic/js/components/file-list/folder-knob.vue
  frontend/classic/js/components/file-list/folder.vue
  frontend/classic/js/components/file-list/index.vue
  frontend/classic/js/components/file-list/span-editable.vue
  frontend/classic/js/components/file-list/tags.vue
  frontend/classic/js/components/hamburger-svg.vue
  frontend/classic/js/components/project-build-status.vue
  frontend/classic/js/components/project-context-menu.vue
  frontend/classic/js/components/project-file-context-menu.vue
  frontend/classic/js/components/project-panel-default-layout.vue
  frontend/classic/js/ide-project.js
  frontend/classic/js/public-path.js
  frontend/node/src/headless.ts
  package-lock.json
  package.json
  webpack.config.js
Labels: kind: cleanup, kind: packaging, part: browser frontend

#415 [deps] [npm] Cleanup and bump dependencies.
  backend/wasm/deps/package-lock.json
  backend/wasm/deps/package.json
  etc/wacoq-deps/package.json
  frontend/cli/build/sdk/setup.ts
  frontend/node/src/headless.ts
  package-lock.json
  package.json
Labels: kind: cleanup, kind: build
